<?php
echo "<!DOCTYPE html>";
echo "<html lang=\"tr\">";
echo "<head>";
echo "<meta charset=\"UTF-8\">";
echo "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
echo "<title>Unspoken Archive | TR</title>";
echo "<style>";
echo "* {";
echo "margin: 0;";
echo "padding: 0;";
echo "box-sizing: border-box;";
echo "}";
echo "";
echo "body {";
echo "font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;";
echo "background: #0d0d0d;";
echo "color: #e0e0e0;";
echo "line-height: 1.6;";
echo "overflow-x: hidden;";
echo "}";
echo "";
echo ".header {";
echo "background: rgba(0, 0, 0, 0.95);";
echo "backdrop-filter: blur(10px);";
echo "border-bottom: 1px solid rgba(255, 255, 255, 0.1);";
echo "position: sticky;";
echo "top: 0;";
echo "z-index: 1000;";
echo "}";
echo "";
echo ".header-container {";
echo "max-width: 1600px;";
echo "margin: 0 auto;";
echo "padding: 0 20px;";
echo "}";
echo "";
echo ".header-top {";
echo "display: flex;";
echo "justify-content: space-between;";
echo "align-items: center;";
echo "padding: 15px 0;";
echo "border-bottom: 1px solid rgba(255, 255, 255, 0.05);";
echo "}";
echo "";
echo ".site-logo {";
echo "display: flex;";
echo "align-items: center;";
echo "gap: 12px;";
echo "}";
echo "";
echo ".logo-icon {";
echo "width: 36px;";
echo "height: 36px;";
echo "background: linear-gradient(135deg, #1a1a1a, #2a2a2a);";
echo "border: 1px solid rgba(255, 255, 255, 0.1);";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "font-weight: bold;";
echo "color: #fff;";
echo "border-radius: 4px;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".site-title {";
echo "font-size: 1.2rem;";
echo "font-weight: 600;";
echo "color: #fff;";
echo "letter-spacing: -0.5px;";
echo "}";
echo "";
echo ".header-actions {";
echo "display: flex;";
echo "gap: 8px;";
echo "}";
echo "";
echo ".header-nav {";
echo "padding: 12px 0;";
echo "overflow-x: auto;";
echo "scrollbar-width: none;";
echo "-ms-overflow-style: none;";
echo "}";
echo "";
echo ".header-nav::-webkit-scrollbar {";
echo "display: none;";
echo "}";
echo "";
echo ".filter-container {";
echo "display: flex;";
echo "gap: 12px;";
echo "padding-bottom: 5px;";
echo "}";
echo "";
echo ".filter-group {";
echo "display: flex;";
echo "flex-direction: column;";
echo "gap: 6px;";
echo "min-width: 140px;";
echo "}";
echo "";
echo ".filter-label {";
echo "color: #888;";
echo "font-size: 0.75rem;";
echo "text-transform: uppercase;";
echo "letter-spacing: 0.5px;";
echo "font-weight: 500;";
echo "white-space: nowrap;";
echo "}";
echo "";
echo "select {";
echo "padding: 8px 30px 8px 12px;";
echo "background: #1a1a1a;";
echo "color: #e0e0e0;";
echo "border: 1px solid rgba(255, 255, 255, 0.1);";
echo "border-radius: 6px;";
echo "font-size: 0.85rem;";
echo "cursor: pointer;";
echo "transition: all 0.3s;";
echo "appearance: none;";
echo "background-image: url(\"data:image/svg+xml,%3Csvg width='12' height='8' viewBox='0 0 12 8' fill='none' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath d='M1 1.5L6 6.5L11 1.5' stroke='%23888' stroke-width='2' stroke-linecap='round'/%3E%3C/svg%3E\");";
echo "background-repeat: no-repeat;";
echo "background-position: right 10px center;";
echo "width: 100%;";
echo "}";
echo "";
echo "select:hover {";
echo "border-color: rgba(255, 255, 255, 0.2);";
echo "background-color: #1f1f1f;";
echo "}";
echo "";
echo "select:focus {";
echo "outline: none;";
echo "border-color: #ff4500;";
echo "box-shadow: 0 0 0 2px rgba(255, 69, 0, 0.1);";
echo "}";
echo "";
echo "button, .btn {";
echo "padding: 8px 16px;";
echo "border-radius: 6px;";
echo "font-size: 0.85rem;";
echo "font-weight: 600;";
echo "cursor: pointer;";
echo "transition: all 0.3s;";
echo "border: 1px solid rgba(255, 255, 255, 0.1);";
echo "background: #1a1a1a;";
echo "color: #fff;";
echo "white-space: nowrap;";
echo "text-decoration: none;";
echo "display: inline-block;";
echo "text-align: center;";
echo "}";
echo "";
echo "button:hover, .btn:hover {";
echo "transform: translateY(-1px);";
echo "background: #222;";
echo "}";
echo "";
echo "button.primary, .btn.primary {";
echo "background: #fff;";
echo "color: #000;";
echo "border: none;";
echo "}";
echo "";
echo "button.primary:hover, .btn.primary:hover {";
echo "background: #e0e0e0;";
echo "}";
echo "";
echo ".main-container {";
echo "max-width: 1600px;";
echo "margin: 0 auto;";
echo "padding: 20px 15px;";
echo "}";
echo "";
echo ".content-grid {";
echo "display: grid;";
echo "grid-template-columns: repeat(auto-fill, minmax(300px, 1fr));";
echo "gap: 20px;";
echo "}";
echo "";
echo ".dosya-card {";
echo "background: #111;";
echo "border-radius: 12px;";
echo "overflow: hidden;";
echo "border: 1px solid rgba(255, 255, 255, 0.05);";
echo "transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);";
echo "cursor: pointer;";
echo "position: relative;";
echo "}";
echo "";
echo ".dosya-card:hover {";
echo "transform: translateY(-8px);";
echo "border-color: rgba(255, 69, 0, 0.4);";
echo "box-shadow: 0 20px 40px rgba(0, 0, 0, 0.4);";
echo "}";
echo "";
echo ".dosya-card.yalan {";
echo "border-left: 3px solid #dc2626;";
echo "}";
echo "";
echo ".dosya-image-container {";
echo "position: relative;";
echo "padding-top: 56.25%;";
echo "background: #000;";
echo "overflow: hidden;";
echo "}";
echo "";
echo ".dosya-image {";
echo "position: absolute;";
echo "top: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 100%;";
echo "object-fit: cover;";
echo "transition: transform 0.6s ease;";
echo "}";
echo "";
echo ".dosya-card:hover .dosya-image {";
echo "transform: scale(1.05);";
echo "}";
echo "";
echo ".yalan-damga {";
echo "position: absolute;";
echo "top: 15px;";
echo "right: 15px;";
echo "width: 60px;";
echo "height: 60px;";
echo "opacity: 0.9;";
echo "z-index: 10;";
echo "filter: drop-shadow(0 4px 8px rgba(0, 0, 0, 0.5));";
echo "}";
echo "";
echo ".dosya-content {";
echo "padding: 18px;";
echo "}";
echo "";
echo ".dosya-header {";
echo "display: flex;";
echo "gap: 8px;";
echo "margin-bottom: 12px;";
echo "flex-wrap: wrap;";
echo "}";
echo "";
echo ".badge {";
echo "padding: 4px 8px;";
echo "border-radius: 4px;";
echo "font-size: 0.7rem;";
echo "font-weight: 600;";
echo "text-transform: uppercase;";
echo "letter-spacing: 0.3px;";
echo "border: 1px solid rgba(255, 255, 255, 0.1);";
echo "}";
echo "";
echo ".badge-tur { border-color: #ff4500; color: #ff4500; }";
echo ".badge-ulke { border-color: #444; color: #aaa; }";
echo ".badge-yalan { background: rgba(220, 38, 38, 0.15); color: #ef4444; border-color: rgba(220, 38, 38, 0.3); }";
echo "";
echo ".dosya-title {";
echo "font-size: 1.1rem;";
echo "font-weight: 700;";
echo "color: #fff;";
echo "margin-bottom: 10px;";
echo "line-height: 1.4;";
echo "}";
echo "";
echo ".dosya-excerpt {";
echo "color: #888;";
echo "font-size: 0.9rem;";
echo "display: -webkit-box;";
echo "-webkit-line-clamp: 3;";
echo "-webkit-box-orient: vertical;";
echo "overflow: hidden;";
echo "}";
echo "";
echo "/* MODAL POPUP */";
echo ".modal {";
echo "display: none;";
echo "position: fixed;";
echo "top: 0;";
echo "left: 0;";
echo "width: 100%;";
echo "height: 100%;";
echo "background: rgba(0, 0, 0, 0.95);";
echo "z-index: 2000;";
echo "overflow-y: auto;";
echo "padding: 20px 10px;";
echo "backdrop-filter: blur(10px);";
echo "}";
echo "";
echo ".modal.active {";
echo "display: block;";
echo "}";
echo "";
echo ".modal-container {";
echo "max-width: 1000px;";
echo "margin: 20px auto;";
echo "background: #0a0a0a;";
echo "border-radius: 16px;";
echo "border: 1px solid rgba(255, 255, 255, 0.1);";
echo "overflow: hidden;";
echo "position: relative;";
echo "}";
echo "";
echo ".modal-gorsel-alani {";
echo "background: #000;";
echo "min-height: 300px;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "border-bottom: 1px solid #222;";
echo "position: relative;";
echo "}";
echo "";
echo ".modal-gorsel-alani img {";
echo "max-width: 100%;";
echo "max-height: 500px;";
echo "object-fit: contain;";
echo "}";
echo "";
echo ".modal-yalan-damga {";
echo "position: absolute;";
echo "top: 20px;";
echo "right: 20px;";
echo "color: #dc2626;";
echo "border: 6px solid #dc2626;";
echo "padding: 15px 25px;";
echo "font-weight: bold;";
echo "transform: rotate(-15deg);";
echo "font-size: 2rem;";
echo "opacity: 0.7;";
echo "pointer-events: none;";
echo "text-shadow: 2px 2px 10px rgba(0,0,0,0.8);";
echo "}";
echo "";
echo ".modal-close {";
echo "position: absolute;";
echo "top: 15px;";
echo "right: 15px;";
echo "width: 36px;";
echo "height: 36px;";
echo "background: rgba(255, 255, 255, 0.1);";
echo "border-radius: 50%;";
echo "display: flex;";
echo "align-items: center;";
echo "justify-content: center;";
echo "cursor: pointer;";
echo "color: #fff;";
echo "font-size: 20px;";
echo "z-index: 10;";
echo "transition: all 0.3s;";
echo "}";
echo "";
echo ".modal-close:hover {";
echo "background: rgba(255, 255, 255, 0.2);";
echo "transform: rotate(90deg);";
echo "}";
echo "";
echo ".modal-content {";
echo "padding: 25px 20px;";
echo "}";
echo "";
echo ".modal-meta {";
echo "display: flex;";
echo "gap: 10px;";
echo "margin-bottom: 20px;";
echo "flex-wrap: wrap;";
echo "}";
echo "";
echo ".modal-title {";
echo "font-size: 1.8rem;";
echo "font-weight: 800;";
echo "color: #fff;";
echo "margin-bottom: 20px;";
echo "letter-spacing: -0.5px;";
echo "line-height: 1.3;";
echo "}";
echo "";
echo ".modal-text {";
echo "font-size: 1rem;";
echo "color: #ccc;";
echo "line-height: 1.7;";
echo "white-space: pre-wrap;";
echo "margin-bottom: 25px;";
echo "}";
echo "";
echo ".modal-footer-links {";
echo "display: flex;";
echo "gap: 12px;";
echo "flex-wrap: wrap;";
echo "}";
echo "";
echo ".modal-belge-link {";
echo "background: #fff;";
echo "color: #000;";
echo "padding: 10px 20px;";
echo "text-decoration: none;";
echo "font-weight: bold;";
echo "border-radius: 5px;";
echo "transition: all 0.3s;";
echo "font-size: 0.9rem;";
echo "display: inline-block;";
echo "}";
echo "";
echo ".modal-belge-link:hover {";
echo "background: #ececec;";
echo "transform: translateY(-2px);";
echo "}";
echo "";
echo ".modal-kaynak-link {";
echo "color: #60a5fa;";
echo "text-decoration: none;";
echo "align-self: center;";
echo "transition: all 0.3s;";
echo "font-size: 0.9rem;";
echo "}";
echo "";
echo ".modal-kaynak-link:hover {";
echo "color: #93c5fd;";
echo "}";
echo "";
echo ".state-message {";
echo "text-align: center;";
echo "padding: 60px 20px;";
echo "color: #888;";
echo "font-size: 1.1rem;";
echo "}";
echo "";
echo "@media (max-width: 768px) {";
echo ".site-title {";
echo "font-size: 1rem;";
echo "}";
echo "";
echo ".logo-icon {";
echo "width: 32px;";
echo "height: 32px;";
echo "font-size: 0.8rem;";
echo "}";
echo "";
echo ".header-top {";
echo "padding: 12px 0;";
echo "}";
echo "";
echo ".header-nav {";
echo "padding: 10px 0;";
echo "}";
echo "";
echo ".filter-container {";
echo "gap: 10px;";
echo "}";
echo "";
echo ".filter-group {";
echo "min-width: 120px;";
echo "}";
echo "";
echo ".filter-label {";
echo "font-size: 0.7rem;";
echo "}";
echo "";
echo "select {";
echo "font-size: 0.8rem;";
echo "padding: 7px 28px 7px 10px;";
echo "}";
echo "";
echo "button, .btn {";
echo "padding: 7px 12px;";
echo "font-size: 0.8rem;";
echo "}";
echo "";
echo ".content-grid {";
echo "grid-template-columns: 1fr;";
echo "gap: 15px;";
echo "}";
echo "";
echo ".dosya-content {";
echo "padding: 15px;";
echo "}";
echo "";
echo ".dosya-title {";
echo "font-size: 1rem;";
echo "}";
echo "";
echo ".dosya-excerpt {";
echo "font-size: 0.85rem;";
echo "}";
echo "";
echo ".yalan-damga {";
echo "width: 50px;";
echo "height: 50px;";
echo "top: 10px;";
echo "right: 10px;";
echo "}";
echo "";
echo ".modal-container {";
echo "margin: 10px auto;";
echo "}";
echo "";
echo ".modal-content {";
echo "padding: 20px 15px;";
echo "}";
echo "";
echo ".modal-title {";
echo "font-size: 1.4rem;";
echo "}";
echo "";
echo ".modal-text {";
echo "font-size: 0.95rem;";
echo "}";
echo "";
echo ".modal-yalan-damga {";
echo "font-size: 1.5rem;";
echo "padding: 10px 18px;";
echo "border: 4px solid #dc2626;";
echo "top: 15px;";
echo "right: 15px;";
echo "}";
echo "";
echo ".modal-gorsel-alani {";
echo "min-height: 200px;";
echo "}";
echo "";
echo ".modal-gorsel-alani img {";
echo "max-height: 350px;";
echo "}";
echo "}";
echo "";
echo "@media (max-width: 480px) {";
echo ".header-container {";
echo "padding: 0 15px;";
echo "}";
echo "";
echo ".main-container {";
echo "padding: 15px 10px;";
echo "}";
echo "";
echo ".site-logo {";
echo "gap: 8px;";
echo "}";
echo "";
echo ".header-actions {";
echo "gap: 5px;";
echo "}";
echo "";
echo "button, .btn {";
echo "padding: 6px 10px;";
echo "font-size: 0.75rem;";
echo "}";
echo "";
echo ".filter-group {";
echo "min-width: 110px;";
echo "}";
echo "";
echo ".modal-title {";
echo "font-size: 1.2rem;";
echo "}";
echo "";
echo ".badge {";
echo "font-size: 0.65rem;";
echo "padding: 3px 6px;";
echo "}";
echo "}";
echo "";
echo "</style>";
echo "</head>";
echo "<body>";
echo "<header class=\"header\">";
echo "<div class=\"header-container\">";
echo "<div class=\"header-top\">";
echo "<div class=\"site-title\">U•Archive</div>";
echo "<div class=\"header-actions\">";
echo "<a href=\"desteklerimiz.html\" class=\"btn\">Desteklerimiz</a>";
echo "</div>";
echo "</div>";
echo "";
echo "<nav class=\"header-nav\">";
echo "<div class=\"filter-container\">";
echo "<div class=\"filter-group\">";
echo "<span class=\"filter-label\">Bölge</span>";
echo "<select id=\"ulkeFilter\">";
echo "<option value=\"\">Tüm Bölgeler</option>";
echo "<optgroup label=\"Avrupa\">";
echo "<option value=\"Almanya\">Almanya</option>";
echo "<option value=\"Fransa\">Fransa</option>";
echo "<option value=\"İngiltere\">İngiltere</option>";
echo "<option value=\"İrlanda\">İrlanda</option>";
echo "<option value=\"İtalya\">İtalya</option>";
echo "<option value=\"İspanya\">İspanya</option>";
echo "</optgroup>";
echo "<optgroup label=\"Asya\">";
echo "<option value=\"Türkiye\">Türkiye</option>";
echo "<option value=\"Bulgaristan\">Bulgaristan</option>";
echo "<option value=\"Yunanistan\">Yunanistan</option>";
echo "</optgroup>";
echo "<optgroup label=\"Amerika\">";
echo "<option value=\"ABD\">Birleşik Devletler</option>";
echo "</optgroup>";
echo "<optgroup label=\"Afrika\">";
echo "<option value=\"Afrika\">Afrika Kıtası</option>";
echo "</optgroup>";
echo "<optgroup label=\"Orta Doğu\">";
echo "<option value=\"Suudi Arabistan\">Suudi Arabistan</option>";
echo "<option value=\"İsrail\">İsrail</option>";
echo "<option value=\"Filistin\">Filistin</option>";
echo "</optgroup>";
echo "<optgroup label=\"Sovyet\">";
echo "<option value=\"SSCB\">SSCB</option>";
echo "</optgroup>";
echo "</select>";
echo "</div>";
echo "";
echo "<div class=\"filter-group\">";
echo "<span class=\"filter-label\">Platform/Grup</span>";
echo "<select id=\"platformFilter\">";
echo "<option value=\"\">Tüm Platformlar</option>";
echo "<optgroup label=\"Sosyal Medya\">";
echo "<option value=\"Discord\">Discord</option>";
echo "<option value=\"Twitter/X\">Twitter/X</option>";
echo "<option value=\"Facebook\">Facebook</option>";
echo "<option value=\"Reddit\">Reddit</option>";
echo "<option value=\"4chan\">4chan</option>";
echo "<option value=\"8chan\">8chan</option>";
echo "<option value=\"Telegram\">Telegram</option>";
echo "<option value=\"WhatsApp\">WhatsApp</option>";
echo "<option value=\"Instagram\">Instagram</option>";
echo "<option value=\"TikTok\">TikTok</option>";
echo "<option value=\"Snapchat\">Snapchat</option>";
echo "</optgroup>";
echo "<optgroup label=\"Hack Grupları\">";
echo "<option value=\"Anonymous\">Anonymous</option>";
echo "<option value=\"LulzSec\">LulzSec</option>";
echo "<option value=\"Lizard Squad\">Lizard Squad</option>";
echo "<option value=\"APT28 (Fancy Bear)\">APT28 (Fancy Bear)</option>";
echo "<option value=\"APT29 (Cozy Bear)\">APT29 (Cozy Bear)</option>";
echo "<option value=\"Lazarus Group\">Lazarus Group</option>";
echo "<option value=\"DarkSide\">DarkSide</option>";
echo "<option value=\"REvil\">REvil</option>";
echo "<option value=\"Conti\">Conti</option>";
echo "<option value=\"Sandworm\">Sandworm</option>";
echo "<option value=\"Killnet\">Killnet</option>";
echo "<option value=\"Ghost Squad Hackers\">Ghost Squad Hackers</option>";
echo "<option value=\"Syrian Electronic Army\">Syrian Electronic Army</option>";
echo "<option value=\"RedHack\">RedHack</option>";
echo "<option value=\"Ayyıldız Tim\">Ayyıldız Tim</option>";
echo "</optgroup>";
echo "<optgroup label=\"Dark/Deep Web\">";
echo "<option value=\"Silk Road\">Silk Road</option>";
echo "<option value=\"AlphaBay\">AlphaBay</option>";
echo "<option value=\"Dream Market\">Dream Market</option>";
echo "<option value=\"Wall Street Market\">Wall Street Market</option>";
echo "<option value=\"Hydra\">Hydra</option>";
echo "<option value=\"Dark Web Forum\">Dark Web Forum</option>";
echo "<option value=\"Onion Site\">Onion Site</option>";
echo "</optgroup>";
echo "<optgroup label=\"Resmi Kaynaklar\">";
echo "<option value=\"Resmi Belge\">Resmi Belge</option>";
echo "<option value=\"Basın\">Basın</option>";
echo "<option value=\"WikiLeaks\">WikiLeaks</option>";
echo "<option value=\"Mahkeme Dosyası\">Mahkeme Dosyası</option>";
echo "<option value=\"Devlet Arşivi\">Devlet Arşivi</option>";
echo "</optgroup>";
echo "<optgroup label=\"Diğer\">";
echo "<option value=\"İncel Forum\">İncel Forum</option>";
echo "<option value=\"Chan Sitesi\">Chan Sitesi</option>";
echo "<option value=\"Underground Forum\">Underground Forum</option>";
echo "<option value=\"Bilinmeyen\">Bilinmeyen</option>";
echo "<option value=\"Diğer\">Diğer</option>";
echo "</optgroup>";
echo "</select>";
echo "</div>";
echo "";
echo "<div class=\"filter-group\">";
echo "<span class=\"filter-label\">Tür</span>";
echo "<select id=\"turFilter\">";
echo "<option value=\"\">Tüm Türler</option>";
echo "<option value=\"Savaş\">Savaş</option>";
echo "<option value=\"Cinayet\">Cinayet</option>";
echo "<option value=\"Esrarengiz Ölüm\">Esrarengiz Ölüm</option>";
echo "<option value=\"Patlama\">Patlama</option>";
echo "<option value=\"Kaza\">Kaza</option>";
echo "<option value=\"Suikast\">Suikast</option>";
echo "<option value=\"Terör\">Terör</option>";
echo "<option value=\"İstihbarat\">İstihbarat</option>";
echo "<option value=\"Sızıntı\">Sızıntı</option>";
echo "<option value=\"Skandal\">Skandal</option>";
echo "<option value=\"Deney\">Deney</option>";
echo "<option value=\"Komplo\">Komplo</option>";
echo "<option value=\"Hack/Siber Saldırı\">Hack/Siber Saldırı</option>";
echo "<option value=\"Uyuşturucu Ticareti\">Uyuşturucu Ticareti</option>";
echo "<option value=\"İnsan Ticareti\">İnsan Ticareti</option>";
echo "<option value=\"Silah Kaçakçılığı\">Silah Kaçakçılığı</option>";
echo "<option value=\"Yolsuzluk\">Yolsuzluk</option>";
echo "<option value=\"Rüşvet\">Rüşvet</option>";
echo "<option value=\"Kara Para Aklama\">Kara Para Aklama</option>";
echo "<option value=\"Organize Suç\">Organize Suç</option>";
echo "<option value=\"Çocuk İstismarı\">Çocuk İstismarı</option>";
echo "<option value=\"Tecavüz\">Tecavüz</option>";
echo "<option value=\"İşkence\">İşkence</option>";
echo "<option value=\"Savaş Suçu\">Savaş Suçu</option>";
echo "<option value=\"Soykırım\">Soykırım</option>";
echo "<option value=\"Etnik Temizlik\">Etnik Temizlik</option>";
echo "<option value=\"Biyolojik Silah\">Biyolojik Silah</option>";
echo "<option value=\"Kimyasal Silah\">Kimyasal Silah</option>";
echo "<option value=\"Nükleer\">Nükleer</option>";
echo "<option value=\"Radyasyon\">Radyasyon</option>";
echo "<option value=\"Zehirlenme\">Zehirlenme</option>";
echo "<option value=\"MK-Ultra\">MK-Ultra</option>";
echo "<option value=\"İnsan Deneyi\">İnsan Deneyi</option>";
echo "<option value=\"Organ Kaçakçılığı\">Organ Kaçakçılığı</option>";
echo "<option value=\"Pedofili Çetesi\">Pedofili Çetesi</option>";
echo "<option value=\"Seri Katil\">Seri Katil</option>";
echo "<option value=\"Kült/Tarikat\">Kült/Tarikat</option>";
echo "<option value=\"Satanizm\">Satanizm</option>";
echo "<option value=\"Okült\">Okült</option>";
echo "<option value=\"UFO/Uzaylı\">UFO/Uzaylı</option>";
echo "<option value=\"Paranormal\">Paranormal</option>";
echo "<option value=\"Deep Web\">Deep Web</option>";
echo "<option value=\"Dark Web\">Dark Web</option>";
echo "<option value=\"Veri Sızıntısı\">Veri Sızıntısı</option>";
echo "<option value=\"Fidye Yazılımı\">Fidye Yazılımı</option>";
echo "<option value=\"DDoS Saldırısı\">DDoS Saldırısı</option>";
echo "<option value=\"Sahte Haber\">Sahte Haber</option>";
echo "<option value=\"Propaganda\">Propaganda</option>";
echo "<option value=\"Psikolojik Harekat\">Psikolojik Harekat</option>";
echo "<option value=\"Casusluk\">Casusluk</option>";
echo "<option value=\"Ajan\">Ajan</option>";
echo "<option value=\"Mossad\">Mossad</option>";
echo "<option value=\"CIA\">CIA</option>";
echo "<option value=\"MI6\">MI6</option>";
echo "<option value=\"KGB\">KGB</option>";
echo "<option value=\"FSB\">FSB</option>";
echo "<option value=\"MİT\">MİT</option>";
echo "<option value=\"Diğer\">Diğer</option>";
echo "</select>";
echo "</div>";
echo "";
echo "";
echo "<div class=\"filter-group\">";
echo "<span class=\"filter-label\">Ortam</span>";
echo "<select id=\"ortamFilter\">";
echo "<option value=\"\">Tüm Ortamlar</option>";
echo "<option value=\"Gerçek Dünya\">Gerçek Dünya</option>";
echo "<option value=\"Sanal Dünya\">Sanal Dünya</option>";
echo "<option value=\"Her İkisi\">Her İkisi</option>";
echo "</select>";
echo "</div>";
echo "";
echo "<div class=\"filter-group\">";
echo "<span class=\"filter-label\">Yıl</span>";
echo "<select id=\"yilFilter\">";
echo "<option value=\"\">Tüm Yıllar</option>";
echo "<option value=\"2024\">2024</option>";
echo "<option value=\"2023\">2023</option>";
echo "<option value=\"2022\">2022</option>";
echo "<option value=\"2021\">2021</option>";
echo "<option value=\"2020\">2020</option>";
echo "<option value=\"2019\">2019</option>";
echo "<option value=\"2018\">2018</option>";
echo "<option value=\"2017\">2017</option>";
echo "<option value=\"2016\">2016</option>";
echo "<option value=\"2015\">2015</option>";
echo "<option value=\"2010-2014\">2010-2014</option>";
echo "<option value=\"2000-2009\">2000-2009</option>";
echo "<option value=\"1990-1999\">1990-1999</option>";
echo "<option value=\"1980-1989\">1980-1989</option>";
echo "<option value=\"1970-1979\">1970-1979</option>";
echo "<option value=\"1960-1969\">1960-1969</option>";
echo "<option value=\"1950-1959\">1950-1959</option>";
echo "<option value=\"1940-1949\">1940-1949</option>";
echo "<option value=\"1930-1939\">1930-1939</option>";
echo "<option value=\"1920-1929\">1920-1929</option>";
echo "<option value=\"1900-1919\">1900-1919</option>";
echo "<option value=\"1800-1899\">1800-1899</option>";
echo "</select>";
echo "</div>";
echo "</nav>";
echo "</div>";
echo "</header>";
echo "";
echo "<main class=\"main-container\">";
echo "<div id=\"belge-listesi\" class=\"content-grid\"></div>";
echo "</main>";
echo "";
echo "<!-- MODAL POPUP -->";
echo "<div id=\"modal-ekran\" class=\"modal\">";
echo "<div class=\"modal-container\">";
echo "<span class=\"modal-close\" onclick=\"kapatModal()\">&times;</span>";
echo "<div id=\"modal-detay\"></div>";
echo "</div>";
echo "</div>";
echo "";
echo "<script src=\"https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2\"></script>";
echo "<script src=\"config.js\"></script>";
echo "<script>";
echo "";
echo "const { createClient } = supabase;";
echo "const supabaseClient = createClient(SUPABASE_CONFIG.url, SUPABASE_CONFIG.key);";
echo "";
echo "const content = document.getElementById('belge-listesi');";
echo "const modal = document.getElementById('modal-ekran');";
echo "const modalDetay = document.getElementById('modal-detay');";
echo "";
echo "const randomBtn = document.getElementById('randomBtn');";
echo "const ulkeFilter = document.getElementById('ulkeFilter');";
echo "const platformFilter = document.getElementById('platformFilter');";
echo "const turFilter = document.getElementById('turFilter');";
echo "const ortamFilter = document.getElementById('ortamFilter');";
echo "const yilFilter = document.getElementById('yilFilter');";
echo "";
echo "// Modal Aç/Kapat";
echo "function acModal(dosya) {";
echo "modalDetay.innerHTML = `";
echo "<div class=\"modal-gorsel-alani\">";
echo "<img src=\"${dosya.belge_url}\" alt=\"${dosya.baslik}\">";
echo "${dosya.yalan_mi ? '<div class=\"modal-yalan-damga\">YALAN</div>' : ''}";
echo "</div>";
echo "<div class=\"modal-content\">";
echo "<div class=\"modal-meta\">";
echo "<span class=\"badge badge-ulke\">${dosya.ulke}</span>";
echo "<span class=\"badge badge-tur\">${dosya.tur}</span>";
echo "${dosya.yalan_mi ? '<span class=\"badge badge-yalan\">YALAN</span>' : ''}";
echo "</div>";
echo "<h1 class=\"modal-title\">${dosya.baslik}</h1>";
echo "<p class=\"modal-text\">${dosya.detay}</p>";
echo "<div class=\"modal-footer-links\">";
echo "<a href=\"${dosya.belge_url}\" target=\"_blank\" class=\"modal-belge-link\">📄 TAM BELGE</a>";
echo "${dosya.kaynak_link ? `<a href=\"${dosya.kaynak_link}\" target=\"_blank\" class=\"modal-kaynak-link\">🔗 Kaynak →</a>` : ''}";
echo "</div>";
echo "${dosya.gazete_haberi ? `<p style=\"margin-top:20px;color:#888;font-size:0.9rem;\">${dosya.gazete_haberi}</p>` : ''}";
echo "</div>";
echo "`;";
echo "modal.classList.add('active');";
echo "document.body.style.overflow = 'hidden';";
echo "}";
echo "";
echo "function kapatModal() {";
echo "modal.classList.remove('active');";
echo "document.body.style.overflow = 'auto';";
echo "}";
echo "";
echo "window.onclick = (e) => {";
echo "if (e.target == modal) kapatModal();";
echo "};";
echo "";
echo "// Belgeleri Listele";
echo "async function arsiviYukle() {";
echo "try {";
echo "let query = supabaseClient.from('gizli_dosyalar').select('*').order('id', { ascending: false });";
echo "";
echo "if (ulkeFilter.value) query = query.eq('ulke', ulkeFilter.value);";
echo "if (platformFilter.value) query = query.eq('platform', platformFilter.value);";
echo "if (turFilter.value) query = query.eq('tur', turFilter.value);";
echo "if (ortamFilter.value) query = query.eq('ortam', ortamFilter.value);";
echo "if (yilFilter.value) query = query.eq('yil', yilFilter.value);";
echo "";
echo "const { data, error } = await query;";
echo "if (error) throw error;";
echo "";
echo "content.innerHTML = '';";
echo "if (data && data.length > 0) {";
echo "data.forEach(dosya => {";
echo "const card = document.createElement('div');";
echo "card.className = `dosya-card ${dosya.yalan_mi ? 'yalan' : ''}`;";
echo "card.onclick = () => acModal(dosya);";
echo "card.innerHTML = `";
echo "<div class=\"dosya-image-container\">";
echo "${dosya.yalan_mi ? '<img src=\"data:image/svg+xml,%3Csvg xmlns=\\'http://www.w3.org/2000/svg\\' viewBox=\\'0 0 200 200\\'%3E%3Ctext x=\\'100\\' y=\\'100\\' text-anchor=\\'middle\\' font-size=\\'60\\' fill=\\'%23dc2626\\' font-weight=\\'bold\\' transform=\\'rotate(-15 100 100)\\'%3EYALAN%3C/text%3E%3C/svg%3E\" class=\"yalan-damga\" alt=\"YALAN\">' : ''}";
echo "<img src=\"${dosya.belge_url}\" class=\"dosya-image\" alt=\"${dosya.baslik}\">";
echo "</div>";
echo "<div class=\"dosya-content\">";
echo "<div class=\"dosya-header\">";
echo "<span class=\"badge badge-tur\">${dosya.tur}</span>";
echo "<span class=\"badge badge-ulke\">${dosya.ulke}</span>";
echo "</div>";
echo "<h3 class=\"dosya-title\">${dosya.baslik}</h3>";
echo "<p class=\"dosya-excerpt\">${dosya.ozet}</p>";
echo "</div>";
echo "`;";
echo "content.appendChild(card);";
echo "});";
echo "} else {";
echo "content.innerHTML = '<div class=\"state-message\">Aranan kriterlere uygun dosya bulunamadı.</div>';";
echo "}";
echo "} catch (err) {";
echo "content.innerHTML = `<div class=\"state-message\" style=\"color:red;\">HATA: ${err.message}</div>`;";
echo "}";
echo "}";
echo "";
echo "// Filtre Değişince Yenile";
echo "[ulkeFilter, platformFilter, turFilter, ortamFilter, yilFilter].forEach(filter => {";
echo "filter.addEventListener('change', arsiviYukle);";
echo "});";
echo "";
echo "// Sayfa Açılınca Hepsini Göster";
echo "window.onload = arsiviYukle;";
echo "";
echo "document.addEventListener('keyup', (e) => {";
echo "if (e.key === 'PrintScreen') {";
echo "navigator.clipboard.writeText('');";
echo "alert('Ekran görüntüsü alma bu sitede engellenmiştir.');";
echo "}";
echo "});";
echo "";
echo "document.addEventListener('keydown', (e) => {";
echo "if (";
echo "(e.ctrlKey && e.shiftKey && e.key === 'S') ||";
echo "(e.metaKey && e.shiftKey && ['3', '4', '5'].includes(e.key)) ||";
echo "(e.metaKey && e.shiftKey && e.key === 's')";
echo ") {";
echo "e.preventDefault();";
echo "alert('Ekran görüntüsü alma bu sitede engellenmiştir.');";
echo "}";
echo "";
echo "if (e.key === 'F12') {";
echo "e.preventDefault();";
echo "return false;";
echo "}";
echo "";
echo "if (e.ctrlKey && e.shiftKey && ['I', 'J', 'C'].includes(e.key)) {";
echo "e.preventDefault();";
echo "return false;";
echo "}";
echo "";
echo "if (e.ctrlKey && e.key === 'u') {";
echo "e.preventDefault();";
echo "return false;";
echo "}";
echo "});";
echo "";
echo "document.addEventListener('contextmenu', (e) => {";
echo "e.preventDefault();";
echo "alert('Sağ tık menüsü bu sitede devre dışıdır.');";
echo "return false;";
echo "});";
echo "";
echo "document.addEventListener('selectstart', (e) => {";
echo "e.preventDefault();";
echo "return false;";
echo "});";
echo "";
echo "document.addEventListener('copy', (e) => {";
echo "e.preventDefault();";
echo "navigator.clipboard.writeText('');";
echo "return false;";
echo "});";
echo "";
echo "document.addEventListener('dragstart', (e) => {";
echo "e.preventDefault();";
echo "return false;";
echo "});";
echo "";
echo "const devtoolsChecker = () => {";
echo "const threshold = 160;";
echo "const widthThreshold = window.outerWidth - window.innerWidth > threshold;";
echo "const heightThreshold = window.outerHeight - window.innerHeight > threshold;";
echo "";
echo "if (widthThreshold || heightThreshold) {";
echo "document.body.innerHTML = '<div style=\"display:flex;align-items:center;justify-content:center;height:100vh;background:#000;color:#f00;font-size:2rem;text-align:center;\">GELİŞTİRİCİ ARAÇLARI TESPİT EDİLDİ<br>ERİŞİM ENGELLENDİ</div>';";
echo "}";
echo "};";
echo "";
echo "setInterval(devtoolsChecker, 1000);";
echo "";
echo "</script>";
echo "</body>";
echo "</html>";
echo "";
?>
